prep:
    total_pixels: 400000
    gamma: 1.0
    canny: [1.1, 0.9]
    hat: 2
    sigmod: [0.6, 5.0]
    struct_element_size: 12
    gauss_blur_size: 21
extract:
    delta: 5
    area_lim: [9, 500]
    variation: 0.25
    channels: ["Gray"]
    direction: 1
    filter_params: 
        flag: ["width", "height", "perimeter", "aspect_ratio", "occupied_ratio", "compactness"] 
        area_lim: 9 
        perimeter_lim: [12, 200]
        aspect_ratio_lim: [1.0, 15.0]
        aspect_ratio_gt1: True
        occupation_lim: [0.15, 0.90]
        compactness_lim: [3e-3, 1e-1]
        width_lim: [0, 800]
        height_lim: [0, 800]
        filter_swt_params:
            total_points: 30
            mode_lim: 1.5
            mean_lim: [2.0, 5.0]
            std_lim: [0.5, 2.5]
