prep:
    total_pixels: 400000
    gamma: 1.0
    canny: [1.1, 0.9]
    hat: 2
    sobel: False
    sigmod: [0.6, 6.0]
    struct_element_size: 12
    gauss_blur_size: 21
extract:
    delta: 5
    area_lim: [9, 500]
    variation: 0.25
    channels: ["Red Channel"]
    direction: 1
mergetl:
    combined_area_size_lim: 400000
    combined_aspect_ratio_lim: [0.0, 99]
    overlap_ratio: 0.25
    distance: 2.6
    strategy: "horizon"
filters:
    extract:
        flag: ["width", "height", "perimeter", "aspect_ratio", "occupied_ratio", "compactness"]
        area_lim: 9 
        perimeter_lim: [12, 200]
        aspect_ratio_lim: [1.0, 15.0]
        aspect_ratio_gt1: True
        occupation_lim: [0.15, 0.90]
        compactness_lim: [3e-3, 1e-1]
        width_lim: [0, 800]
        height_lim: [0, 800]
    morph:
        flag: ['area']
        area_lim: 9
