# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/app.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.display_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_widget.sizePolicy().hasHeightForWidth())
        self.display_widget.setSizePolicy(sizePolicy)
        self.display_widget.setObjectName("display_widget")
        self.horizontalLayout.addWidget(self.display_widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.botton_layout = QtWidgets.QHBoxLayout()
        self.botton_layout.setObjectName("botton_layout")
        self.btn_locate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_locate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_locate.setObjectName("btn_locate")
        self.botton_layout.addWidget(self.btn_locate)
        self.btn_recognize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_recognize.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_recognize.setObjectName("btn_recognize")
        self.botton_layout.addWidget(self.btn_recognize)
        self.verticalLayout.addLayout(self.botton_layout)
        self.plain_text_edit_output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text_edit_output.setMaximumSize(QtCore.QSize(16777215, 150))
        self.plain_text_edit_output.setObjectName("plain_text_edit_output")
        self.verticalLayout.addWidget(self.plain_text_edit_output)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_settings = QtWidgets.QMenu(self.menubar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menuStage = QtWidgets.QMenu(self.menubar)
        self.menuStage.setObjectName("menuStage")
        MainWindow.setMenuBar(self.menubar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_load_config = QtWidgets.QAction(MainWindow)
        self.action_load_config.setObjectName("action_load_config")
        self.action_preferences = QtWidgets.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.action_save_config = QtWidgets.QAction(MainWindow)
        self.action_save_config.setObjectName("action_save_config")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_open_current_control_panel = QtWidgets.QAction(MainWindow)
        self.action_open_current_control_panel.setObjectName("action_open_current_control_panel")
        self.action_preprocessing = QtWidgets.QAction(MainWindow)
        self.action_preprocessing.setCheckable(True)
        self.action_preprocessing.setChecked(False)
        self.action_preprocessing.setObjectName("action_preprocessing")
        self.action_extract_connect_domain = QtWidgets.QAction(MainWindow)
        self.action_extract_connect_domain.setCheckable(True)
        self.action_extract_connect_domain.setChecked(False)
        self.action_extract_connect_domain.setObjectName("action_extract_connect_domain")
        self.action_merging_text_line = QtWidgets.QAction(MainWindow)
        self.action_merging_text_line.setCheckable(True)
        self.action_merging_text_line.setObjectName("action_merging_text_line")
        self.action_identify_with_feature = QtWidgets.QAction(MainWindow)
        self.action_identify_with_feature.setCheckable(True)
        self.action_identify_with_feature.setObjectName("action_identify_with_feature")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_settings.addAction(self.action_load_config)
        self.menu_settings.addAction(self.action_save_config)
        self.menu_settings.addAction(self.action_preferences)
        self.menu_settings.addAction(self.action_open_current_control_panel)
        self.menu_help.addAction(self.action_about)
        self.menuStage.addAction(self.action_preprocessing)
        self.menuStage.addAction(self.action_extract_connect_domain)
        self.menuStage.addAction(self.action_merging_text_line)
        self.menuStage.addAction(self.action_identify_with_feature)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menuStage.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Detection"))
        self.btn_locate.setText(_translate("MainWindow", "Locate"))
        self.btn_recognize.setText(_translate("MainWindow", "Recognize"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_settings.setTitle(_translate("MainWindow", "Settings"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menuStage.setTitle(_translate("MainWindow", "Stage"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
        self.action_load_config.setText(_translate("MainWindow", "Load Config"))
        self.action_preferences.setText(_translate("MainWindow", "Preferences"))
        self.action_save_config.setText(_translate("MainWindow", "Save Config"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.action_open_current_control_panel.setText(_translate("MainWindow", "Open Current Control Panel"))
        self.action_preprocessing.setText(_translate("MainWindow", "Preprocessing"))
        self.action_extract_connect_domain.setText(_translate("MainWindow", "Extract Connect-Domain"))
        self.action_merging_text_line.setText(_translate("MainWindow", "Merging Text Line"))
        self.action_identify_with_feature.setText(_translate("MainWindow", "Identify with Feature"))
