# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extract_control.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExtractCtrlWidget(object):
    def setupUi(self, ExtractCtrlWidget):
        ExtractCtrlWidget.setObjectName("ExtractCtrlWidget")
        ExtractCtrlWidget.setWindowModality(QtCore.Qt.NonModal)
        ExtractCtrlWidget.resize(588, 713)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExtractCtrlWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_mser_params = QtWidgets.QFormLayout()
        self.layout_mser_params.setObjectName("layout_mser_params")
        self.label_mser_params = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_mser_params.setObjectName("label_mser_params")
        self.layout_mser_params.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_mser_params)
        self.label_mser_delta = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mser_delta.sizePolicy().hasHeightForWidth())
        self.label_mser_delta.setSizePolicy(sizePolicy)
        self.label_mser_delta.setMinimumSize(QtCore.QSize(180, 0))
        self.label_mser_delta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mser_delta.setObjectName("label_mser_delta")
        self.layout_mser_params.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_mser_delta)
        self.spinbox_mser_delta = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_mser_delta.setProperty("value", 5)
        self.spinbox_mser_delta.setObjectName("spinbox_mser_delta")
        self.layout_mser_params.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinbox_mser_delta)
        self.label_mser_area_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mser_area_lim.sizePolicy().hasHeightForWidth())
        self.label_mser_area_lim.setSizePolicy(sizePolicy)
        self.label_mser_area_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_mser_area_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mser_area_lim.setObjectName("label_mser_area_lim")
        self.layout_mser_params.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_mser_area_lim)
        self.layout_mser_area_lim = QtWidgets.QHBoxLayout()
        self.layout_mser_area_lim.setObjectName("layout_mser_area_lim")
        self.label_mser_area_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mser_area_high.sizePolicy().hasHeightForWidth())
        self.label_mser_area_high.setSizePolicy(sizePolicy)
        self.label_mser_area_high.setObjectName("label_mser_area_high")
        self.layout_mser_area_lim.addWidget(self.label_mser_area_high)
        self.spinbox_mser_area_high = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_mser_area_high.setMaximum(10000000)
        self.spinbox_mser_area_high.setProperty("value", 500)
        self.spinbox_mser_area_high.setObjectName("spinbox_mser_area_high")
        self.layout_mser_area_lim.addWidget(self.spinbox_mser_area_high)
        self.label_mser_area_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mser_area_low.sizePolicy().hasHeightForWidth())
        self.label_mser_area_low.setSizePolicy(sizePolicy)
        self.label_mser_area_low.setObjectName("label_mser_area_low")
        self.layout_mser_area_lim.addWidget(self.label_mser_area_low)
        self.spinbox_mser_area_low = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_mser_area_low.setMaximum(10000000)
        self.spinbox_mser_area_low.setProperty("value", 9)
        self.spinbox_mser_area_low.setObjectName("spinbox_mser_area_low")
        self.layout_mser_area_lim.addWidget(self.spinbox_mser_area_low)
        self.layout_mser_params.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.layout_mser_area_lim)
        self.label_mser_variation = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mser_variation.sizePolicy().hasHeightForWidth())
        self.label_mser_variation.setSizePolicy(sizePolicy)
        self.label_mser_variation.setMinimumSize(QtCore.QSize(180, 0))
        self.label_mser_variation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mser_variation.setObjectName("label_mser_variation")
        self.layout_mser_params.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_mser_variation)
        self.dspinbox_mser_variation = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_mser_variation.setMaximum(1.0)
        self.dspinbox_mser_variation.setProperty("value", 0.25)
        self.dspinbox_mser_variation.setObjectName("dspinbox_mser_variation")
        self.layout_mser_params.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dspinbox_mser_variation)
        self.label_mser_channels = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_mser_channels.setMinimumSize(QtCore.QSize(180, 0))
        self.label_mser_channels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mser_channels.setObjectName("label_mser_channels")
        self.layout_mser_params.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_mser_channels)
        self.layout_channels_options = QtWidgets.QHBoxLayout()
        self.layout_channels_options.setObjectName("layout_channels_options")
        self.checkbox_mser_gray = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_mser_gray.setChecked(True)
        self.checkbox_mser_gray.setObjectName("checkbox_mser_gray")
        self.layout_channels_options.addWidget(self.checkbox_mser_gray)
        self.checkbox_mser_red = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_mser_red.setObjectName("checkbox_mser_red")
        self.layout_channels_options.addWidget(self.checkbox_mser_red)
        self.checkbox_mser_green = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_mser_green.setObjectName("checkbox_mser_green")
        self.layout_channels_options.addWidget(self.checkbox_mser_green)
        self.checkbox_mser_blue = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_mser_blue.setObjectName("checkbox_mser_blue")
        self.layout_channels_options.addWidget(self.checkbox_mser_blue)
        self.layout_mser_params.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.layout_channels_options)
        self.label_mser_debug = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_mser_debug.setMinimumSize(QtCore.QSize(180, 0))
        self.label_mser_debug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mser_debug.setObjectName("label_mser_debug")
        self.layout_mser_params.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_mser_debug)
        self.checkbox_mser_debug_enable = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_mser_debug_enable.setObjectName("checkbox_mser_debug_enable")
        self.layout_mser_params.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkbox_mser_debug_enable)
        self.verticalLayout.addLayout(self.layout_mser_params)
        self.layout_filter_params = QtWidgets.QFormLayout()
        self.layout_filter_params.setObjectName("layout_filter_params")
        self.label_filter_params = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_params.setObjectName("label_filter_params")
        self.layout_filter_params.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_filter_params)
        self.label_filter_enable = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_enable.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_enable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_enable.setObjectName("label_filter_enable")
        self.layout_filter_params.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_filter_enable)
        self.checkbox_filter_enable = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_filter_enable.setChecked(True)
        self.checkbox_filter_enable.setObjectName("checkbox_filter_enable")
        self.layout_filter_params.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkbox_filter_enable)
        self.label_filter_area_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_area_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_area_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_area_lim.setObjectName("label_filter_area_lim")
        self.layout_filter_params.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_filter_area_lim)
        self.label_filter_perimeter_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_perimeter_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_perimeter_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_perimeter_lim.setObjectName("label_filter_perimeter_lim")
        self.layout_filter_params.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_filter_perimeter_lim)
        self.label_filter_aspect_ratio_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_aspect_ratio_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_aspect_ratio_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_aspect_ratio_lim.setObjectName("label_filter_aspect_ratio_lim")
        self.layout_filter_params.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_filter_aspect_ratio_lim)
        self.layout_aspect_ratio_lim = QtWidgets.QHBoxLayout()
        self.layout_aspect_ratio_lim.setObjectName("layout_aspect_ratio_lim")
        self.label_filter_aspect_ratio_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_aspect_ratio_high.sizePolicy().hasHeightForWidth())
        self.label_filter_aspect_ratio_high.setSizePolicy(sizePolicy)
        self.label_filter_aspect_ratio_high.setObjectName("label_filter_aspect_ratio_high")
        self.layout_aspect_ratio_lim.addWidget(self.label_filter_aspect_ratio_high)
        self.dspinbox_filter_aspect_ratio_high = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_aspect_ratio_high.setMinimumSize(QtCore.QSize(100, 0))
        self.dspinbox_filter_aspect_ratio_high.setProperty("value", 15.0)
        self.dspinbox_filter_aspect_ratio_high.setObjectName("dspinbox_filter_aspect_ratio_high")
        self.layout_aspect_ratio_lim.addWidget(self.dspinbox_filter_aspect_ratio_high)
        self.label_filter_aspect_ratio_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_aspect_ratio_low.sizePolicy().hasHeightForWidth())
        self.label_filter_aspect_ratio_low.setSizePolicy(sizePolicy)
        self.label_filter_aspect_ratio_low.setObjectName("label_filter_aspect_ratio_low")
        self.layout_aspect_ratio_lim.addWidget(self.label_filter_aspect_ratio_low)
        self.dspinbox_filter_aspect_ratio_low = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_aspect_ratio_low.setMinimumSize(QtCore.QSize(100, 0))
        self.dspinbox_filter_aspect_ratio_low.setProperty("value", 1.0)
        self.dspinbox_filter_aspect_ratio_low.setObjectName("dspinbox_filter_aspect_ratio_low")
        self.layout_aspect_ratio_lim.addWidget(self.dspinbox_filter_aspect_ratio_low)
        self.checkbox_filter_aspect_ratio_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_aspect_ratio_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_aspect_ratio_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_aspect_ratio_lim.setChecked(True)
        self.checkbox_filter_aspect_ratio_lim.setObjectName("checkbox_filter_aspect_ratio_lim")
        self.layout_aspect_ratio_lim.addWidget(self.checkbox_filter_aspect_ratio_lim)
        self.layout_filter_params.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.layout_aspect_ratio_lim)
        self.label_filter_occupation_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_occupation_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_occupation_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_occupation_lim.setObjectName("label_filter_occupation_lim")
        self.layout_filter_params.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_filter_occupation_lim)
        self.layout_occupation_lim = QtWidgets.QHBoxLayout()
        self.layout_occupation_lim.setObjectName("layout_occupation_lim")
        self.label_filter_occupation_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_occupation_high.sizePolicy().hasHeightForWidth())
        self.label_filter_occupation_high.setSizePolicy(sizePolicy)
        self.label_filter_occupation_high.setObjectName("label_filter_occupation_high")
        self.layout_occupation_lim.addWidget(self.label_filter_occupation_high)
        self.dspinbox_filter_occupation_high = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_occupation_high.setMinimumSize(QtCore.QSize(100, 0))
        self.dspinbox_filter_occupation_high.setProperty("value", 0.9)
        self.dspinbox_filter_occupation_high.setObjectName("dspinbox_filter_occupation_high")
        self.layout_occupation_lim.addWidget(self.dspinbox_filter_occupation_high)
        self.label_filter_occupation_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_occupation_low.sizePolicy().hasHeightForWidth())
        self.label_filter_occupation_low.setSizePolicy(sizePolicy)
        self.label_filter_occupation_low.setObjectName("label_filter_occupation_low")
        self.layout_occupation_lim.addWidget(self.label_filter_occupation_low)
        self.dspinbox_filter_occupation_low = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_occupation_low.setMinimumSize(QtCore.QSize(100, 0))
        self.dspinbox_filter_occupation_low.setProperty("value", 0.15)
        self.dspinbox_filter_occupation_low.setObjectName("dspinbox_filter_occupation_low")
        self.layout_occupation_lim.addWidget(self.dspinbox_filter_occupation_low)
        self.checkbox_filter_occupation_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_occupation_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_occupation_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_occupation_lim.setChecked(True)
        self.checkbox_filter_occupation_lim.setObjectName("checkbox_filter_occupation_lim")
        self.layout_occupation_lim.addWidget(self.checkbox_filter_occupation_lim)
        self.layout_filter_params.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.layout_occupation_lim)
        self.label_filter_compactness_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_compactness_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_compactness_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_compactness_lim.setObjectName("label_filter_compactness_lim")
        self.layout_filter_params.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_filter_compactness_lim)
        self.label_filter_width_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_width_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_width_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_width_lim.setObjectName("label_filter_width_lim")
        self.layout_filter_params.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_filter_width_lim)
        self.label_filter_height_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_height_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_height_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_height_lim.setObjectName("label_filter_height_lim")
        self.layout_filter_params.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_filter_height_lim)
        self.label_filter_swt_filter_enable = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_swt_filter_enable.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_swt_filter_enable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_swt_filter_enable.setObjectName("label_filter_swt_filter_enable")
        self.layout_filter_params.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_filter_swt_filter_enable)
        self.checkbox_filter_swt_filter_enable = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_filter_swt_filter_enable.setObjectName("checkbox_filter_swt_filter_enable")
        self.layout_filter_params.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.checkbox_filter_swt_filter_enable)
        self.label_filter_swt_total_points = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_swt_total_points.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_swt_total_points.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_swt_total_points.setObjectName("label_filter_swt_total_points")
        self.layout_filter_params.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_filter_swt_total_points)
        self.label_filter_swt_mode_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_swt_mode_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_swt_mode_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_swt_mode_lim.setObjectName("label_filter_swt_mode_lim")
        self.layout_filter_params.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_filter_swt_mode_lim)
        self.label_filter_swt_mean_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_swt_mean_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_swt_mean_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_swt_mean_lim.setObjectName("label_filter_swt_mean_lim")
        self.layout_filter_params.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_filter_swt_mean_lim)
        self.layout_filter_swt_mean_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_swt_mean_lim.setObjectName("layout_filter_swt_mean_lim")
        self.label_filter_swt_mean_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_swt_mean_high.sizePolicy().hasHeightForWidth())
        self.label_filter_swt_mean_high.setSizePolicy(sizePolicy)
        self.label_filter_swt_mean_high.setObjectName("label_filter_swt_mean_high")
        self.layout_filter_swt_mean_lim.addWidget(self.label_filter_swt_mean_high)
        self.dspinbox_filter_swt_mean_high = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_swt_mean_high.setProperty("value", 5.0)
        self.dspinbox_filter_swt_mean_high.setObjectName("dspinbox_filter_swt_mean_high")
        self.layout_filter_swt_mean_lim.addWidget(self.dspinbox_filter_swt_mean_high)
        self.label_filter_swt_mean_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_swt_mean_low.sizePolicy().hasHeightForWidth())
        self.label_filter_swt_mean_low.setSizePolicy(sizePolicy)
        self.label_filter_swt_mean_low.setObjectName("label_filter_swt_mean_low")
        self.layout_filter_swt_mean_lim.addWidget(self.label_filter_swt_mean_low)
        self.dspinbox_filter_swt_mean_low = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_swt_mean_low.setProperty("value", 2.0)
        self.dspinbox_filter_swt_mean_low.setObjectName("dspinbox_filter_swt_mean_low")
        self.layout_filter_swt_mean_lim.addWidget(self.dspinbox_filter_swt_mean_low)
        self.layout_filter_params.setLayout(16, QtWidgets.QFormLayout.FieldRole, self.layout_filter_swt_mean_lim)
        self.layout_filter_compactness_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_compactness_lim.setObjectName("layout_filter_compactness_lim")
        self.label_filter_compactness_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_compactness_high.sizePolicy().hasHeightForWidth())
        self.label_filter_compactness_high.setSizePolicy(sizePolicy)
        self.label_filter_compactness_high.setObjectName("label_filter_compactness_high")
        self.layout_filter_compactness_lim.addWidget(self.label_filter_compactness_high)
        self.dspinbox_filter_compactness_high = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_compactness_high.setMinimumSize(QtCore.QSize(100, 0))
        self.dspinbox_filter_compactness_high.setProperty("value", 0.1)
        self.dspinbox_filter_compactness_high.setObjectName("dspinbox_filter_compactness_high")
        self.layout_filter_compactness_lim.addWidget(self.dspinbox_filter_compactness_high)
        self.label_filter_compactness_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_compactness_low.sizePolicy().hasHeightForWidth())
        self.label_filter_compactness_low.setSizePolicy(sizePolicy)
        self.label_filter_compactness_low.setObjectName("label_filter_compactness_low")
        self.layout_filter_compactness_lim.addWidget(self.label_filter_compactness_low)
        self.dspinbox_filter_compactness_low = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_compactness_low.setMinimumSize(QtCore.QSize(100, 0))
        self.dspinbox_filter_compactness_low.setDecimals(3)
        self.dspinbox_filter_compactness_low.setSingleStep(0.001)
        self.dspinbox_filter_compactness_low.setProperty("value", 0.003)
        self.dspinbox_filter_compactness_low.setObjectName("dspinbox_filter_compactness_low")
        self.layout_filter_compactness_lim.addWidget(self.dspinbox_filter_compactness_low)
        self.checkbox_filter_compactness_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_compactness_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_compactness_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_compactness_lim.setChecked(True)
        self.checkbox_filter_compactness_lim.setObjectName("checkbox_filter_compactness_lim")
        self.layout_filter_compactness_lim.addWidget(self.checkbox_filter_compactness_lim)
        self.layout_filter_params.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.layout_filter_compactness_lim)
        self.label_filter_swt_std_lim = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_swt_std_lim.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_swt_std_lim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_swt_std_lim.setObjectName("label_filter_swt_std_lim")
        self.layout_filter_params.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_filter_swt_std_lim)
        self.layout_filter_swt_std_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_swt_std_lim.setObjectName("layout_filter_swt_std_lim")
        self.label_filter_swt_std_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_swt_std_high.sizePolicy().hasHeightForWidth())
        self.label_filter_swt_std_high.setSizePolicy(sizePolicy)
        self.label_filter_swt_std_high.setObjectName("label_filter_swt_std_high")
        self.layout_filter_swt_std_lim.addWidget(self.label_filter_swt_std_high)
        self.dspinbox_filter_swt_std_high = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_swt_std_high.setProperty("value", 2.5)
        self.dspinbox_filter_swt_std_high.setObjectName("dspinbox_filter_swt_std_high")
        self.layout_filter_swt_std_lim.addWidget(self.dspinbox_filter_swt_std_high)
        self.label_filter_swt_std_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_swt_std_low.sizePolicy().hasHeightForWidth())
        self.label_filter_swt_std_low.setSizePolicy(sizePolicy)
        self.label_filter_swt_std_low.setObjectName("label_filter_swt_std_low")
        self.layout_filter_swt_std_lim.addWidget(self.label_filter_swt_std_low)
        self.dspinbox_filter_swt_std_low = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_swt_std_low.setProperty("value", 0.5)
        self.dspinbox_filter_swt_std_low.setObjectName("dspinbox_filter_swt_std_low")
        self.layout_filter_swt_std_lim.addWidget(self.dspinbox_filter_swt_std_low)
        self.layout_filter_params.setLayout(17, QtWidgets.QFormLayout.FieldRole, self.layout_filter_swt_std_lim)
        self.spinbox_filter_swt_total_points = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_filter_swt_total_points.setProperty("value", 30)
        self.spinbox_filter_swt_total_points.setObjectName("spinbox_filter_swt_total_points")
        self.layout_filter_params.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.spinbox_filter_swt_total_points)
        self.dspinbox_filter_swt_mode_lim = QtWidgets.QDoubleSpinBox(ExtractCtrlWidget)
        self.dspinbox_filter_swt_mode_lim.setProperty("value", 1.5)
        self.dspinbox_filter_swt_mode_lim.setObjectName("dspinbox_filter_swt_mode_lim")
        self.layout_filter_params.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.dspinbox_filter_swt_mode_lim)
        self.label = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label.setObjectName("label")
        self.layout_filter_params.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_filter_debug = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_debug.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_debug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_debug.setObjectName("label_filter_debug")
        self.layout_filter_params.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_filter_debug)
        self.checkbox_filter_debug = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_filter_debug.setObjectName("checkbox_filter_debug")
        self.layout_filter_params.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkbox_filter_debug)
        self.layout_filter_width_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_width_lim.setObjectName("layout_filter_width_lim")
        self.label_filter_width_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_width_high.sizePolicy().hasHeightForWidth())
        self.label_filter_width_high.setSizePolicy(sizePolicy)
        self.label_filter_width_high.setObjectName("label_filter_width_high")
        self.layout_filter_width_lim.addWidget(self.label_filter_width_high)
        self.spinbox_filter_width_high = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_filter_width_high.setMinimumSize(QtCore.QSize(100, 0))
        self.spinbox_filter_width_high.setMaximum(10000000)
        self.spinbox_filter_width_high.setProperty("value", 800)
        self.spinbox_filter_width_high.setObjectName("spinbox_filter_width_high")
        self.layout_filter_width_lim.addWidget(self.spinbox_filter_width_high)
        self.label_filter_width_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_width_low.sizePolicy().hasHeightForWidth())
        self.label_filter_width_low.setSizePolicy(sizePolicy)
        self.label_filter_width_low.setObjectName("label_filter_width_low")
        self.layout_filter_width_lim.addWidget(self.label_filter_width_low)
        self.spinbox_filter_width_low = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_filter_width_low.setMinimumSize(QtCore.QSize(100, 0))
        self.spinbox_filter_width_low.setObjectName("spinbox_filter_width_low")
        self.layout_filter_width_lim.addWidget(self.spinbox_filter_width_low)
        self.checkbox_filter_width_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_width_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_width_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_width_lim.setChecked(True)
        self.checkbox_filter_width_lim.setObjectName("checkbox_filter_width_lim")
        self.layout_filter_width_lim.addWidget(self.checkbox_filter_width_lim)
        self.layout_filter_params.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.layout_filter_width_lim)
        self.layout_filter_height_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_height_lim.setObjectName("layout_filter_height_lim")
        self.label_filter_height_high = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_height_high.sizePolicy().hasHeightForWidth())
        self.label_filter_height_high.setSizePolicy(sizePolicy)
        self.label_filter_height_high.setObjectName("label_filter_height_high")
        self.layout_filter_height_lim.addWidget(self.label_filter_height_high)
        self.spinbox_filter_height_high = QtWidgets.QSpinBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_filter_height_high.sizePolicy().hasHeightForWidth())
        self.spinbox_filter_height_high.setSizePolicy(sizePolicy)
        self.spinbox_filter_height_high.setMinimumSize(QtCore.QSize(100, 0))
        self.spinbox_filter_height_high.setMaximum(10000000)
        self.spinbox_filter_height_high.setProperty("value", 800)
        self.spinbox_filter_height_high.setObjectName("spinbox_filter_height_high")
        self.layout_filter_height_lim.addWidget(self.spinbox_filter_height_high)
        self.label_filter_height_low = QtWidgets.QLabel(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter_height_low.sizePolicy().hasHeightForWidth())
        self.label_filter_height_low.setSizePolicy(sizePolicy)
        self.label_filter_height_low.setObjectName("label_filter_height_low")
        self.layout_filter_height_lim.addWidget(self.label_filter_height_low)
        self.spinbox_filter_height_low = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_filter_height_low.setMinimumSize(QtCore.QSize(100, 0))
        self.spinbox_filter_height_low.setObjectName("spinbox_filter_height_low")
        self.layout_filter_height_lim.addWidget(self.spinbox_filter_height_low)
        self.checkbox_filter_height_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_height_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_height_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_height_lim.setChecked(True)
        self.checkbox_filter_height_lim.setObjectName("checkbox_filter_height_lim")
        self.layout_filter_height_lim.addWidget(self.checkbox_filter_height_lim)
        self.layout_filter_params.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.layout_filter_height_lim)
        self.layout_filter_area_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_area_lim.setObjectName("layout_filter_area_lim")
        self.spinbox_filter_area_lim = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_filter_area_lim.setMaximum(10000000)
        self.spinbox_filter_area_lim.setProperty("value", 20000)
        self.spinbox_filter_area_lim.setObjectName("spinbox_filter_area_lim")
        self.layout_filter_area_lim.addWidget(self.spinbox_filter_area_lim)
        self.checkbox_filter_area_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_area_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_area_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_area_lim.setChecked(True)
        self.checkbox_filter_area_lim.setObjectName("checkbox_filter_area_lim")
        self.layout_filter_area_lim.addWidget(self.checkbox_filter_area_lim)
        self.layout_filter_params.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.layout_filter_area_lim)
        self.layout_filter_perimeter_lim = QtWidgets.QHBoxLayout()
        self.layout_filter_perimeter_lim.setObjectName("layout_filter_perimeter_lim")
        self.spinbox_filter_perimeter_lim = QtWidgets.QSpinBox(ExtractCtrlWidget)
        self.spinbox_filter_perimeter_lim.setProperty("value", 12)
        self.spinbox_filter_perimeter_lim.setObjectName("spinbox_filter_perimeter_lim")
        self.layout_filter_perimeter_lim.addWidget(self.spinbox_filter_perimeter_lim)
        self.checkbox_filter_perimeter_lim = QtWidgets.QCheckBox(ExtractCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_filter_perimeter_lim.sizePolicy().hasHeightForWidth())
        self.checkbox_filter_perimeter_lim.setSizePolicy(sizePolicy)
        self.checkbox_filter_perimeter_lim.setChecked(True)
        self.checkbox_filter_perimeter_lim.setObjectName("checkbox_filter_perimeter_lim")
        self.layout_filter_perimeter_lim.addWidget(self.checkbox_filter_perimeter_lim)
        self.layout_filter_params.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.layout_filter_perimeter_lim)
        self.label_filter_abs_aspect_ratio = QtWidgets.QLabel(ExtractCtrlWidget)
        self.label_filter_abs_aspect_ratio.setMinimumSize(QtCore.QSize(180, 0))
        self.label_filter_abs_aspect_ratio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filter_abs_aspect_ratio.setObjectName("label_filter_abs_aspect_ratio")
        self.layout_filter_params.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_filter_abs_aspect_ratio)
        self.checkbox_filter_abs_aspect_ratio = QtWidgets.QCheckBox(ExtractCtrlWidget)
        self.checkbox_filter_abs_aspect_ratio.setObjectName("checkbox_filter_abs_aspect_ratio")
        self.layout_filter_params.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkbox_filter_abs_aspect_ratio)
        self.verticalLayout.addLayout(self.layout_filter_params)
        self.btn_ok = QtWidgets.QPushButton(ExtractCtrlWidget)
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ExtractCtrlWidget)
        QtCore.QMetaObject.connectSlotsByName(ExtractCtrlWidget)

    def retranslateUi(self, ExtractCtrlWidget):
        _translate = QtCore.QCoreApplication.translate
        ExtractCtrlWidget.setWindowTitle(_translate("ExtractCtrlWidget", "Extract Control Panel"))
        self.label_mser_params.setText(_translate("ExtractCtrlWidget", "MSER Params"))
        self.label_mser_delta.setText(_translate("ExtractCtrlWidget", "delta :"))
        self.label_mser_area_lim.setText(_translate("ExtractCtrlWidget", "Area Lim :"))
        self.label_mser_area_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_mser_area_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.label_mser_variation.setText(_translate("ExtractCtrlWidget", "Variation :"))
        self.label_mser_channels.setText(_translate("ExtractCtrlWidget", "Channels :"))
        self.checkbox_mser_gray.setText(_translate("ExtractCtrlWidget", "Gray"))
        self.checkbox_mser_red.setText(_translate("ExtractCtrlWidget", "Red"))
        self.checkbox_mser_green.setText(_translate("ExtractCtrlWidget", "Green"))
        self.checkbox_mser_blue.setText(_translate("ExtractCtrlWidget", "Blue"))
        self.label_mser_debug.setText(_translate("ExtractCtrlWidget", "Debug :"))
        self.checkbox_mser_debug_enable.setText(_translate("ExtractCtrlWidget", "Debug Enable"))
        self.label_filter_params.setText(_translate("ExtractCtrlWidget", "Filter Params"))
        self.label_filter_enable.setText(_translate("ExtractCtrlWidget", " Filter Enable :"))
        self.checkbox_filter_enable.setText(_translate("ExtractCtrlWidget", "Filter Enable"))
        self.label_filter_area_lim.setText(_translate("ExtractCtrlWidget", "Area Lim :"))
        self.label_filter_perimeter_lim.setText(_translate("ExtractCtrlWidget", "Perimeter Lim :"))
        self.label_filter_aspect_ratio_lim.setText(_translate("ExtractCtrlWidget", "Aspect Ratio Lim :"))
        self.label_filter_aspect_ratio_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_aspect_ratio_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.checkbox_filter_aspect_ratio_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.label_filter_occupation_lim.setText(_translate("ExtractCtrlWidget", "Occupation Lim :"))
        self.label_filter_occupation_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_occupation_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.checkbox_filter_occupation_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.label_filter_compactness_lim.setText(_translate("ExtractCtrlWidget", "Compactness Lim :"))
        self.label_filter_width_lim.setText(_translate("ExtractCtrlWidget", "Width Lim :"))
        self.label_filter_height_lim.setText(_translate("ExtractCtrlWidget", "Height Lim :"))
        self.label_filter_swt_filter_enable.setText(_translate("ExtractCtrlWidget", "SWT Filter Enable :"))
        self.checkbox_filter_swt_filter_enable.setText(_translate("ExtractCtrlWidget", "SWT Filter Enable"))
        self.label_filter_swt_total_points.setText(_translate("ExtractCtrlWidget", "Total Points:"))
        self.label_filter_swt_mode_lim.setText(_translate("ExtractCtrlWidget", "Mode Lim :"))
        self.label_filter_swt_mean_lim.setText(_translate("ExtractCtrlWidget", "Mean Lim :"))
        self.label_filter_swt_mean_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_swt_mean_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.label_filter_compactness_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_compactness_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.checkbox_filter_compactness_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.label_filter_swt_std_lim.setText(_translate("ExtractCtrlWidget", "Std Lim :"))
        self.label_filter_swt_std_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_swt_std_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.label.setText(_translate("ExtractCtrlWidget", "SWT Filter Params"))
        self.label_filter_debug.setText(_translate("ExtractCtrlWidget", " Filter Debug :"))
        self.checkbox_filter_debug.setText(_translate("ExtractCtrlWidget", "Debug Enable"))
        self.label_filter_width_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_width_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.checkbox_filter_width_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.label_filter_height_high.setText(_translate("ExtractCtrlWidget", "High:"))
        self.label_filter_height_low.setText(_translate("ExtractCtrlWidget", "Low:"))
        self.checkbox_filter_height_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.checkbox_filter_area_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.checkbox_filter_perimeter_lim.setText(_translate("ExtractCtrlWidget", "Enable"))
        self.label_filter_abs_aspect_ratio.setText(_translate("ExtractCtrlWidget", "Abs Aspect Ratio :"))
        self.checkbox_filter_abs_aspect_ratio.setText(_translate("ExtractCtrlWidget", "Absolute Aspect Ratio"))
        self.btn_ok.setText(_translate("ExtractCtrlWidget", "OK"))
