# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/verbose_show.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VerboseDisplay(object):
    def setupUi(self, VerboseDisplay):
        VerboseDisplay.setObjectName("VerboseDisplay")
        VerboseDisplay.resize(1028, 597)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VerboseDisplay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_display = QtWidgets.QWidget(VerboseDisplay)
        self.widget_display.setObjectName("widget_display")
        self.horizontalLayout.addWidget(self.widget_display)
        self.line_vertical_1 = QtWidgets.QFrame(VerboseDisplay)
        self.line_vertical_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_vertical_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_vertical_1.setObjectName("line_vertical_1")
        self.horizontalLayout.addWidget(self.line_vertical_1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_widget_sec = QtWidgets.QListWidget(VerboseDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_widget_sec.sizePolicy().hasHeightForWidth())
        self.list_widget_sec.setSizePolicy(sizePolicy)
        self.list_widget_sec.setMinimumSize(QtCore.QSize(200, 0))
        self.list_widget_sec.setMaximumSize(QtCore.QSize(200, 16777215))
        self.list_widget_sec.setObjectName("list_widget_sec")
        self.horizontalLayout_2.addWidget(self.list_widget_sec)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_sources = QtWidgets.QLabel(VerboseDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sources.sizePolicy().hasHeightForWidth())
        self.label_sources.setSizePolicy(sizePolicy)
        self.label_sources.setMinimumSize(QtCore.QSize(200, 0))
        self.label_sources.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_sources.setObjectName("label_sources")
        self.verticalLayout.addWidget(self.label_sources)
        self.combo_sources = QtWidgets.QComboBox(VerboseDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_sources.sizePolicy().hasHeightForWidth())
        self.combo_sources.setSizePolicy(sizePolicy)
        self.combo_sources.setMinimumSize(QtCore.QSize(200, 0))
        self.combo_sources.setMaximumSize(QtCore.QSize(200, 16777215))
        self.combo_sources.setObjectName("combo_sources")
        self.verticalLayout.addWidget(self.combo_sources)
        self.line_horiz_1 = QtWidgets.QFrame(VerboseDisplay)
        self.line_horiz_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horiz_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horiz_1.setObjectName("line_horiz_1")
        self.verticalLayout.addWidget(self.line_horiz_1)
        self.list_widget = QtWidgets.QListWidget(VerboseDisplay)
        self.list_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.list_widget.setObjectName("list_widget")
        self.verticalLayout.addWidget(self.list_widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_horiz_2 = QtWidgets.QFrame(VerboseDisplay)
        self.line_horiz_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horiz_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horiz_2.setObjectName("line_horiz_2")
        self.verticalLayout_3.addWidget(self.line_horiz_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkbox_use_final_ret_as_bg = QtWidgets.QCheckBox(VerboseDisplay)
        self.checkbox_use_final_ret_as_bg.setMinimumSize(QtCore.QSize(150, 0))
        self.checkbox_use_final_ret_as_bg.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkbox_use_final_ret_as_bg.setObjectName("checkbox_use_final_ret_as_bg")
        self.horizontalLayout_3.addWidget(self.checkbox_use_final_ret_as_bg)
        self.checkbox_color_keep = QtWidgets.QCheckBox(VerboseDisplay)
        self.checkbox_color_keep.setMinimumSize(QtCore.QSize(150, 0))
        self.checkbox_color_keep.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkbox_color_keep.setObjectName("checkbox_color_keep")
        self.horizontalLayout_3.addWidget(self.checkbox_color_keep)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line_horiz_3 = QtWidgets.QFrame(VerboseDisplay)
        self.line_horiz_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horiz_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horiz_3.setObjectName("line_horiz_3")
        self.verticalLayout_3.addWidget(self.line_horiz_3)
        self.textbrowser_info = QtWidgets.QTextBrowser(VerboseDisplay)
        self.textbrowser_info.setEnabled(True)
        self.textbrowser_info.setMaximumSize(QtCore.QSize(411, 16777215))
        self.textbrowser_info.setObjectName("textbrowser_info")
        self.verticalLayout_3.addWidget(self.textbrowser_info)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(4, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(VerboseDisplay)
        QtCore.QMetaObject.connectSlotsByName(VerboseDisplay)

    def retranslateUi(self, VerboseDisplay):
        _translate = QtCore.QCoreApplication.translate
        VerboseDisplay.setWindowTitle(_translate("VerboseDisplay", "Verbose Result"))
        self.label_sources.setText(_translate("VerboseDisplay", "Sources:"))
        self.checkbox_use_final_ret_as_bg.setText(_translate("VerboseDisplay", "Use Final Ret as BG"))
        self.checkbox_color_keep.setText(_translate("VerboseDisplay", "Color Keep"))
        self.textbrowser_info.setHtml(_translate("VerboseDisplay", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Info:</p></body></html>"))
